### PR TITLE
MTDSA-700 self employment annual summary

### PR DESCRIPTION
**Pull request by alexec**

### CODE REVIEW

**Comment by saurabharora80** [comment]
PUT /self-assessment/nino/{nino}/self-employments/{selfEmploymentId}/{taxYear} 400 response doesn't have an error example.

**Comment by saurabharora80** [comment]
PUT /self-assessment/nino/{nino}/self-employments/{selfEmploymentId}/{taxYear} example body should have amounts pounds and pence. e.g "basisAdjustment" should be 500.00. This just makes for a better example. 
Same applies to the response of GET /self-assessment/nino/{nino}/self-employments/{selfEmploymentId}/{taxYear}

**Comment by alexec** [comment]
Updated based on @saurabharora80 feedback.

**Comment by andyws** [comment]
Seems like a small point but are we really ever interested in pence in the new world or the current world for that matter?

**Comment by alexec** [comment]
Hi @andyws - thank you for your feedback. The API will accept financial amounts to 2dp (i.e pounds and pence). Whether or not we require you to submit in pounds and pence is a policy question. I'll raise with the programme.

**Comment by saurabharora80** [comment]
@alexec Looks alright.

**Comment by alexec** [comment]
Closing and replacing with freshly branded PR.

**Pull request closed without merging**
