### PR TITLE
MTDSA-696 self-employment periods

### PR DESCRIPTION
**Pull request by alexec**

### CODE REVIEW

**Comment by saurabharora80** [comment]
POST /self-assessment/nino/{nino}/self-employments/periods 400 error response should include example and example values in the body should be in Pounds and Pence to make it look more realistic. 
GET /self-assessment/nino/{nino}/self-employments/periods/{periodId} 200 response doesn't have an example. 
PUT /self-assessment/nino/{nino}/self-employments/periods/{periodId} example values in the body should be in Pounds and Pence to make it look more realistic.

**Comment by alexec** [comment]
> POST /self-assessment/nino/{nino}/self-employments/periods 400 error response should include example and example values in the body should be in Pounds and Pence to make it look more realistic. 

Interesting. A JSON number does not need a .00 suffix as it does not have rounding issues you find in other languages. However, perhaps adding 25p to each amount will make it clearer.

> GET /self-assessment/nino/{nino}/self-employments/periods/{periodId} 200 response doesn't have an example. 

Will fix.

> PUT /self-assessment/nino/{nino}/self-employments/periods/{periodId} example values in the body should be in Pounds and Pence to make it look more realistic.

See above.

**Comment by alexec** [comment]
Updated based on @saurabharora80 feedback.

**Comment by saurabharora80** [comment]
@alexec /self-assessment/nino/{nino}/self-employments/periods and /self-assessment/nino/{nino}/self-employments/periods/{periodId} are missing the {sourceId} after self-employments!

**Comment by saurabharora80** [comment]
Why do we still have "_embedded"!? I thought we agreed that it only makes sense in the a HAL world.

**Comment by saurabharora80** [comment]
Best not to let the user update the period date i.e 'from' and 'to' dates should not be a part of PUT as this could cause complication and a lot of validation on our side.

**Comment by alexec** [comment]
Deleting and replacing with new branch.

**Pull request closed without merging**
